### PR TITLE
Remove mock generation from generate-from-swagger

### PR DESCRIPTION
**Pull request by filanov**
Delete generated mockery mocks

### CODE REVIEW

**Comment by filanov** [comment]
```
Ran 39 of 39 Specs in 538.816 seconds
SUCCESS! -- 39 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSubsystem (538.82s)
PASS
```

**Comment by avishayt** [comment]
@filanov What is the point of this commit?  The files aren't used?

**Comment by filanov** [comment]
> @filanov What is the point of this commit? The files aren't used?

Yes, it was part of a conversation that we had in the slack. No one is using those files. 
and we have a better way to create a mock
https://coreos.slack.com/archives/CUPJTHQ5P/p1594554385006500

**Comment by avishayt** [comment]
Ran 38 of 38 Specs in 445.070 seconds
SUCCESS! -- 38 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSubsystem (445.08s)
PASS
ok  	github.com/filanov/bm-inventory/subsystem	445.115s

**Pull request merged**
