### PR TITLE
Avishay/mgmt 948

### PR DESCRIPTION
**Pull request by avishayt**

### CODE REVIEW

**Comment by filanov** [comment]
@avishayt what will happen if the value already exists in the DB and the user didn't pass any parameters?

**Comment by avishayt** [comment]
> @avishayt what will happen if the value already exists in the DB and the user didn't pass any parameters?

Any values that aren't passed get deleted, that's the semantics of PUT, and that's how the user can reset properties back to their default values.

**Comment by filanov** [comment]
> > @avishayt what will happen if the value already exists in the DB and the user didn't pass any parameters?
> 
> Any values that aren't passed get deleted, that's the semantics of PUT, and that's how the user can reset properties back to their default values.

it's a big change, does UI and test-infra ready for it? subsystem as well.

**Comment by avishayt** [comment]
> > > @avishayt what will happen if the value already exists in the DB and the user didn't pass any parameters?
> > 
> > 
> > Any values that aren't passed get deleted, that's the semantics of PUT, and that's how the user can reset properties back to their default values.
> 
> it's a big change, does UI and test-infra ready for it? subsystem as well.

**Comment by avishayt** [comment]
Looking into alternatives

**Comment by filanov** [comment]
i'm not saying that we should not do it. just want to be sure that we don't break anything.

**Pull request closed without merging**
