### PR TITLE
MGMT-905 assisted install container should be named explicitly

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by eranco74** [comment]
Surprisingly all UT and subsystem passed.
`
Ran 17 of 17 Specs in 69.005 seconds
SUCCESS! -- 17 Passed | 0 Failed | 0 Pending | 0 Skipped
`
We have no coverage for the install command?

**Comment by yevgeny-shnaidman** [comment]
probably there is a lot of coverage missing. Maybe, after 1of June, we should take a couple of days to update test coverage for most of the repositories

**Comment by filanov** [comment]
@eranco74 isn't there UT test that can validate that we pass the right format?

**Comment by filanov** [comment]
subsystem don't check it because it's not actually running this code.

**Comment by eranco74** [comment]
All UT passed, I didn't changed them - hence no coverage.

**Comment by filanov** [comment]
so maybe you should add a test that check that we don't break the format of the command?

**Comment by eranco74** [comment]
Can I get an approve PR this PR regardless of the missing tests?

**Pull request merged**
