### PR TITLE
Pass the host-id to the install command

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by filanov** [comment]
@eranco74 is the agent doing something with it?

**Comment by eranco74** [comment]
The agent need it for publishing the progress...

**Comment by filanov** [comment]
But does he already know how get this flag?

**Comment by eranco74** [comment]
> But does he already know how get this flag?
This is the install command, the assisted-installer get's it, it's required for publishing the host install progress

**Comment by filanov** [comment]
> > But does he already know how get this flag?
> > This is the install command, the assisted-installer get's it, it's required for publishing the host install progress

sorry i was thinking it was the ignition. my bad

**Pull request merged**
