### PR TITLE
Updated bootstrap stages

### PR DESCRIPTION
**Pull request by eranco74**
Removed HostStageFinishWaitingForControlPlane
Moved HostStageStartWaitingForControlPlane, to be after HostStageWritingImageToDisk,

### CODE REVIEW

**Comment by romfreiman** [comment]
Ticket?

**Comment by eranco74** [comment]
> Ticket?
MGMT-1482
In the branch name...

**Comment by eranco74** [comment]
http://10.0.9.195:8080/job/test-infra/1709/parameters/

**Comment by eranco74** [comment]
http://10.0.9.195:8080/job/test-infra/1747/

**Pull request merged**
