### PR TITLE
Moved the logic that check the cluster status when trying to download…

### PR DESCRIPTION
**Pull request by eranco74**
… a file or get credentials to clustrApi

### CODE REVIEW

**Comment by tsorya** [comment]
To say the truth it doesn't look good. Not sure why moving this part is so crucial, i think it looks even less readable than now and much more complicated.
Not better just to add function :
validate_cluster_state(cluster.., allowed_states) ?

**Comment by eranco74** [comment]
> validate_cluster_state(cluster.., allowed_states) ?

I agree, but than the inventory needs to know (as it did till now) what are the allowed statuses for each action.
@filanov ?

**Comment by filanov** [comment]
@eranco74 is that just the first step? because it's strange that get function return just an error.

**Comment by filanov** [comment]
if it is the first step then please add a TODO in the API or somewhere so it will be clear.

**Comment by filanov** [comment]
> To say the truth it doesn't look good. Not sure why moving this part is so crucial, i think it looks even less readable than now and much more complicated.
> Not better just to add function :
> validate_cluster_state(cluster.., allowed_states) ?

As @eranco74 said, cluster status is something internal to the cluster. so it should be handled by the cluster.

**Comment by eranco74** [comment]
Next step:
https://issues.redhat.com/browse/MGMT-1031

**Pull request merged**
