### PR TITLE
Preparing the Role and service to be fully compatible with Prometheus monitoring

### PR DESCRIPTION
**Pull request by jparrill**
Those changes are necesary in order to add the monitoring part on the Minikube side.
After these ones, you need to follow this steps:

- Deploy OLM
- Deploy Prometheus operator
- Deploy Prometheus instance
- Create the service of the Assisted Installer for Prometheus
- Create the ServiceMonitor

With that you will be able to see the monitoring screen on your cluster using a port-forward

### CODE REVIEW

**Comment by filanov** [comment]
is it tested with test-infra?

**Comment by jparrill** [comment]
It's not a destructive change, it just ask for more permissions on the Role creation and gives a name for the port in the svc case. Should work in the same way.

**Comment by romfreiman** [comment]
@jparrill just verifying that it will run on ocp with all the restrictions there

**Comment by jparrill** [comment]
Humm It should, this seems like an error from the Jenkins api token against GitHub, could be?

**Comment by jparrill** [comment]
is this a permissions issue on the destination CI/CD platform?

**Comment by filanov** [comment]
@jparrill i added you as a contributor. lets see if it helps.

**Pull request merged**
